.TH gprename 1 "May 24, 2007"
.SH NAME
gprename \- complete batch renamer for Linux
.SH SYNOPSIS
.B gprename
.I directory
.SH DESCRIPTION
This manual page documents briefly the
.B gprename
command.
.PP
\fBgprename\fP is a complete batch renamer for files and directories, coded for Linux in GTK2-Perl. GPRename is licensed under the terms of the GNU General Public Licence. GPRename features many options to rename in batch, such as replace, remove, insert or delete text, add numbers consecutively and is available in many languages.
.br
.SH FILES
~/.gprename			User configuration text file
.br
~/.gprename_log		User log text file
.SH AUTHOR
gprename was written by Tristesse <tristesse@users.sourceforge.net> but is currently developed by Zurd <zurd@users.sourceforge.net>.
.br
This manual page was written by Marvin Stark <marv@der-marv.de>.
